apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "erlang-soap"
  description: "Erlang SOAP support - Make it easy to use SOAP"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-claims-operations"
  system: prima.it
