name: CI

on: push

jobs:
  build:
    name: Build & Test (OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [21, 22, 23, 24, 25] # many tests fail on OTP 26

    container: erlang:${{ matrix.otp }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Rebar cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-erlang-${{ matrix.otp }}-${{ hashFiles('**/*rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-erlang-${{ matrix.otp }}-

      - name: Dialyzer
        run: rebar3 dialyzer

      - name: Run tests
        run: make ct
