name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: erlang:21
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make ct
