name: Publish to Hex

on:
  release:
    types: [published]

jobs:
  erlang-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4
      - name: Install Beam/OTP/Elixir
        uses: erlef/setup-beam@v1
        id: setup-erlang
        with:
          otp-version: 26.0
          rebar3-version: 3.24.0
      - name: Login to hex.pm
        run: rebar3 hex organization auth hexpm:prima --key ${{ secrets.HEX_KEY }}
        env:
          HEX_HOME: ./_build/.hex
      - name: Install dependencies
        run: rebar3 update; rebar3 deps
      - name: Publish to Hex.pm
        run: rebar3 hex publish -r hexpm:prima --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_KEY }}
          HEX_HOME: ./_build/.hex
