name: Publish to Hex

on:
  release:
    types: [published]

jobs:
  erlang-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Publish to Hex"
        uses: ./.github/actions/erlang-publish
        with:
          runs-on: ubuntu-latest
          rebar3-version: 3.24.0
          otp-version: 26.0
          HEX_KEY: ${{ secrets.HEX_KEY }}